### ISSUE TITLE
APK version number wrong?

### ISSUE THREAD

**Issue by IzzySoft** [moosd/NetworkGhost#2]
Just curious: the `.apk` attached to release 1.1 identifies itself as 1.0:

```
package: name='com.moosd.netghost' versionCode='1' versionName='1.0'
```

Some error in the Manifest – or is it the wrong file? :stuck_out_tongue_winking_eye:

**Comment by souramoo** [comment]
Oops, that's just me being lazy and not updating `build.gradle`. :P Fixed in 1.2!

**Comment by IzzySoft** [comment]
Thanks! Will check as soon as time permits (hopefully this evening). So you're still actively on it, and a 1.3 can be expected some day? Don't want to "push" – I know how one can be kept busy with multiple projects (happens to me all the time ;)

**Comment by IzzySoft** [comment]
PS: You forgot the `versionCode`. That still sticks on `1` and thus keeps the problem alive :)
